import {lazy,Suspense,useCallback,useEffect,useRef,useState} from 'react';
import {Panel} from './forge-ui/Panel';
import {api} from './services/api';
import type {Diagnostic,Project,Provider,Workspace} from './types';
const Viewport=lazy(()=>import('./viewport/Viewport').then(m=>({default:m.Viewport})));
const initial:Workspace={grid:true,environment:true,overlays:true,camera:[12,4,12],target:[0,0,0]};
function stored(){try{return JSON.parse(localStorage.getItem('forge.panel')||'{}')}catch{return {}}}
export function App(){
 const [projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState<Project|null>(null),[workspace,setWorkspace]=useState(initial);
 const [tab,setTab]=useState(stored().tab||'Criar'),[closed,setClosed]=useState(stored().closed===true),[clean,setClean]=useState(false),[focus,setFocus]=useState(0);
 const [name,setName]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState('Conectando…'),[online,setOnline]=useState(false),[providers,setProviders]=useState<Provider[]>([]),[diagnostic,setDiagnostic]=useState<Diagnostic|null>(null),[busy,setBusy]=useState(false);
 const [dirty,setDirty]=useState(false);const saving=useRef(false);const current=useRef({project,workspace,name});current.current={project,workspace,name};
 const generation=useRef(0);
 const load=useCallback(async()=>{try{const [p,h,engines]=await Promise.all([api<Project[]>('/projects'),api<{status:string}>('/health'),api<Provider[]>('/providers')]);setProjects(p);setOnline(h.status==='ok');setProviders(engines);setStatus('Pronto · armazenamento local');setError('');const id=localStorage.getItem('forge.project');const selected=p.find(p=>p.id===id);if(selected){setProject(selected);setWorkspace(selected.workspace);setName(selected.name)}}catch(e){setOnline(false);setStatus('Backend desconectado');setError((e as Error).message)}},[]);
 useEffect(()=>{void load()},[load]);
 const save=useCallback(async()=>{
  const snapshot=current.current;if(!snapshot.project||saving.current)return;
  saving.current=true;const ticket=generation.current;setStatus('Salvando…');
  try{const result=await api<Project>(`/projects/${snapshot.project.id}`,'PUT',{name:snapshot.name,revision:snapshot.project.revision,workspace:snapshot.workspace});setProject(result);setProjects(p=>p.map(item=>item.id===result.id?result:item));if(ticket===generation.current)setDirty(false);setStatus('Salvo neste computador');setError('')}
  catch(e){setStatus('Não salvo');setError((e as Error).message)}finally{saving.current=false}
 },[]);
 useEffect(()=>{if(!dirty)return;const timer=setTimeout(()=>void save(),1000);return()=>clearTimeout(timer)},[dirty,workspace,name,project,save]);
 useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave)},[dirty]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select'))return;if(e.key==='Tab'){e.preventDefault();setClean(v=>!v)}if(e.key.toLowerCase()==='f')setFocus(v=>v+1);if(e.key==='Escape')setClean(false)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 function edit(w:Workspace){setWorkspace(w);if(project){generation.current++;setDirty(true)}}
 async function select(id:string){if(dirty||saving.current){setError('Aguarde o salvamento antes de trocar de projeto.');return}try{const p=await api<Project>(`/projects/${id}`);setProject(p);setName(p.name);setWorkspace(p.workspace);localStorage.setItem('forge.project',p.id);setError('')}catch(e){setError((e as Error).message)}}
 async function create(){if(!name.trim()||busy||dirty)return;setBusy(true);try{const p=await api<Project>('/projects','POST',{name});setProject(p);setWorkspace(p.workspace);setProjects(items=>[p,...items]);localStorage.setItem('forge.project',p.id);setName(p.name);setStatus('Projeto criado');setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function inspect(){setBusy(true);try{setDiagnostic(await api<Diagnostic>('/diagnostics'));setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{if(tab==='Diagnóstico'&&!diagnostic)void inspect()},[tab]);
 const camera=useCallback((camera:number[],target:number[])=>{setWorkspace(w=>({...w,camera,target}));if(current.current.project){generation.current++;setDirty(true)}},[]);
 return <main>
  <Suspense fallback={<div className="loading">Abrindo viewport…</div>}><Viewport workspace={workspace} onCamera={camera} focus={focus}/></Suspense>
  {!clean&&<><header className="topbar"><div className="wordmark"><span className="brand-icon">F</span>FORGE<span className="edition">ESTÚDIO 3D</span></div><div className="project-title"><span className="muted">Projeto / </span>{project?.name||'Novo espaço de criação'}{dirty&&<span className="dot"> •</span>}</div><button className="local-badge" onClick={()=>{setTab('Diagnóstico');setClosed(false)}}><i className={online?'online':''}/> {online?'Local · conectado':'Sem conexão'}</button></header>
  <div className="viewport-label"><span className="tiny-label">ESPAÇO DE CRIAÇÃO</span><h1>Uma ideia. Infinitas formas.</h1><p>Seu próximo mundo começa aqui.</p></div>
  <aside className="view-tools" aria-label="Controles da viewport"><button title="Centralizar câmera (F)" onClick={()=>setFocus(v=>v+1)}>⌖</button><button title="Exibir grade" aria-pressed={workspace.grid} onClick={()=>edit({...workspace,grid:!workspace.grid})}>▦</button><button title="Exibir ambiente" aria-pressed={workspace.environment} onClick={()=>edit({...workspace,environment:!workspace.environment})}>☀</button><button title="Exibir informações" aria-pressed={workspace.overlays} onClick={()=>edit({...workspace,overlays:!workspace.overlays})}>i</button><span/><button title="Modo limpo (Tab)" onClick={()=>setClean(true)}>⛶</button></aside>
  {workspace.overlays&&<><div className="orientation"><span className="axis-y">Y</span><span className="axis-z">Z</span><span className="axis-x">X</span><small>EIXOS DO MUNDO</small></div></>}
  <Panel hidden={closed} tab={tab} onTab={setTab} onClose={()=>setClosed(true)}>
   {tab==='Criar'&&<><div className="eyebrow">DA IDEIA AO SEU PRÓXIMO ASSET</div><h2>O que vamos criar?</h2><p className="description">Um espaço para transformar suas ideias em mundos, personagens e objetos.</p><div className="prompt-placeholder"><span>Descreva o que você imagina…</span><span className="phase">DISPONÍVEL NA FASE 2</span></div><div className="input-modes"><span>↗ Imagem</span><span>⌁ Sketch</span><span>✦ Concept</span></div><button className="primary" disabled>Gerar concept <span>↗</span></button><div className="notice"><span className="notice-icon">◇</span><div><strong>Vamos preparar seu espaço</strong><p>{project?'Seu projeto está salvo. A geração por IA será conectada na próxima fase.':'Crie ou abra um projeto para salvar seu espaço de trabalho neste computador.'}</p><button className="text-button" onClick={()=>setTab('Projeto')}>{project?'Abrir projeto':'Criar meu primeiro projeto'} →</button></div></div><div className="section-label">MOTORES LOCAIS</div>{providers.map(p=><div className="provider" key={p.id}><span>{p.name}</span><span className="tag">Não configurado</span></div>)}</>}
   {tab==='Projeto'&&<><div className="eyebrow">SEU ESPAÇO, NO SEU COMPUTADOR</div><h2>Projetos</h2><label className="field">Nome do projeto<input maxLength={100} value={name} placeholder="Ex.: Floresta de cristal" onChange={e=>{setName(e.target.value);if(project){generation.current++;setDirty(true)}}}/></label><div className="button-row"><button className="primary" disabled={!online||busy||!name.trim()||dirty||Boolean(project)} onClick={()=>void create()}>Criar projeto</button><button disabled={!project||!dirty||!name.trim()} onClick={()=>void save()}>Salvar agora</button></div>{project&&<p className="help">Editar o nome renomeia o projeto atual. Para criar outro, use “Novo projeto”.</p>}{project&&<button disabled={dirty} onClick={()=>{setProject(null);setName('');setWorkspace(initial);localStorage.removeItem('forge.project')}}>+ Novo projeto</button>}<div className="section-label">NESTE COMPUTADOR · {projects.length}</div><div className="project-list">{projects.map(p=><button className={p.id===project?.id?'selected':''} key={p.id} onClick={()=>void select(p.id)}><span>◇ <strong>{p.name}</strong><small>{new Date(p.updated_at).toLocaleString('pt-BR')}</small></span><span>↗</span></button>)}</div><div className="empty-state"><span>◇</span><strong>{project?'Seu projeto ainda não possui assets.':'Nenhum projeto aberto.'}</strong><p>{project?'Concepts, modelos e versões aparecerão aqui quando forem criados.':'Crie um projeto ou selecione um da lista.'}</p></div></>}
   {(tab==='Modelo'||tab==='Efeitos')&&<><div className="eyebrow">{tab==='Modelo'?'EDIÇÃO CONTEXTUAL':'MOVIMENTO E ATMOSFERA'}</div><h2>{tab==='Modelo'?'Seu asset, em detalhes.':'Dê vida à sua criação.'}</h2><div className="empty-state"><span>{tab==='Modelo'?'◇':'✧'}</span><strong>{tab==='Modelo'?'Nenhum modelo no projeto':'Nenhum efeito no projeto'}</strong><p>{tab==='Modelo'?'A geração e importação de modelos entram nas próximas fases. Esta viewport já é um ambiente 3D real.':'Partículas, shaders e animações serão integrados na Fase 8.'}</p></div><button onClick={()=>setTab('Criar')}>Voltar para Criar →</button></>}
   {tab==='Diagnóstico'&&<><div className="eyebrow">INFRAESTRUTURA LOCAL</div><h2>Diagnóstico</h2><p className="description">Informações consultadas neste computador. Nenhum modelo é baixado automaticamente.</p><button disabled={busy} onClick={()=>void inspect()}>{busy?'Verificando…':'Atualizar diagnóstico'}</button>{diagnostic&&<dl className="diagnostics"><dt>Sistema</dt><dd>{diagnostic.os}</dd><dt>CPU</dt><dd>{diagnostic.cpu} · {diagnostic.cores} threads</dd><dt>Memória RAM</dt><dd>{(diagnostic.ram_bytes/1024**3).toFixed(1)} GB</dd><dt>GPU</dt><dd>{diagnostic.gpu.devices.map(g=><div key={g.name}>{g.name}<br/>{g.vram_mb} MB · driver {g.driver}</div>)}{!diagnostic.gpu.devices.length&&diagnostic.gpu.status}</dd><dt>CUDA</dt><dd>{diagnostic.cuda}</dd><dt>Python</dt><dd>{diagnostic.python}</dd><dt>Blender</dt><dd>{diagnostic.blender||'Não detectado no PATH'}</dd><dt>ComfyUI</dt><dd>{diagnostic.comfyui}</dd><dt>Armazenamento</dt><dd>{diagnostic.storage}<br/>{(diagnostic.free_bytes/1024**3).toFixed(1)} GB livres</dd></dl>}<div className="notice"><div><strong>Somente local</strong><p>Sem telemetria, créditos ou envio de projetos a terceiros.</p></div></div></>}
  </Panel>
  {closed&&<button className="reopen primary" onClick={()=>setClosed(false)}>F / Abrir FORGE</button>}
  <footer className="statusbar"><span><i className={online?'online':''}/>{status}</span><span>Orbitar: arraste · Pan: botão direito · Zoom: rolagem</span><span>Metros <b>·</b> Foco <kbd>F</kbd> Modo limpo <kbd>Tab</kbd></span></footer></>}
  {clean&&<button className="exit-clean" onClick={()=>setClean(false)}>Voltar ao estúdio <kbd>Tab</kbd></button>}
  {error&&<div className="error-toast" role="alert"><span>{error}</span>{!online&&<button onClick={()=>void load()}>Reconectar</button>}<button aria-label="Fechar erro" onClick={()=>setError('')}>×</button></div>}
 </main>
}

